(cl:defpackage c_srv-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "PROCESSDATA"
   "<PROCESSDATA-REQUEST>"
   "PROCESSDATA-REQUEST"
   "<PROCESSDATA-RESPONSE>"
   "PROCESSDATA-RESPONSE"
  ))

