// Generated by gencpp from file custome_msgs_pkg/personaldata.msg
// DO NOT EDIT!


#ifndef CUSTOME_MSGS_PKG_MESSAGE_PERSONALDATA_H
#define CUSTOME_MSGS_PKG_MESSAGE_PERSONALDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custome_msgs_pkg
{
template <class ContainerAllocator>
struct personaldata_
{
  typedef personaldata_<ContainerAllocator> Type;

  personaldata_()
    : name()
    , age(0)
    , score(0.0)
    , active(false)  {
    }
  personaldata_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , score(0.0)
    , active(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _age_type;
  _age_type age;

   typedef float _score_type;
  _score_type score;

   typedef uint8_t _active_type;
  _active_type active;





  typedef boost::shared_ptr< ::custome_msgs_pkg::personaldata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custome_msgs_pkg::personaldata_<ContainerAllocator> const> ConstPtr;

}; // struct personaldata_

typedef ::custome_msgs_pkg::personaldata_<std::allocator<void> > personaldata;

typedef boost::shared_ptr< ::custome_msgs_pkg::personaldata > personaldataPtr;
typedef boost::shared_ptr< ::custome_msgs_pkg::personaldata const> personaldataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custome_msgs_pkg::personaldata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custome_msgs_pkg::personaldata_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custome_msgs_pkg::personaldata_<ContainerAllocator1> & lhs, const ::custome_msgs_pkg::personaldata_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.score == rhs.score &&
    lhs.active == rhs.active;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custome_msgs_pkg::personaldata_<ContainerAllocator1> & lhs, const ::custome_msgs_pkg::personaldata_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custome_msgs_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custome_msgs_pkg::personaldata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custome_msgs_pkg::personaldata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custome_msgs_pkg::personaldata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custome_msgs_pkg::personaldata_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custome_msgs_pkg::personaldata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custome_msgs_pkg::personaldata_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custome_msgs_pkg::personaldata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "061349f55a78627d0345fee97c4f7854";
  }

  static const char* value(const ::custome_msgs_pkg::personaldata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x061349f55a78627dULL;
  static const uint64_t static_value2 = 0x0345fee97c4f7854ULL;
};

template<class ContainerAllocator>
struct DataType< ::custome_msgs_pkg::personaldata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custome_msgs_pkg/personaldata";
  }

  static const char* value(const ::custome_msgs_pkg::personaldata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custome_msgs_pkg::personaldata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 age\n"
"float32 score\n"
"bool active\n"
;
  }

  static const char* value(const ::custome_msgs_pkg::personaldata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custome_msgs_pkg::personaldata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.score);
      stream.next(m.active);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct personaldata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custome_msgs_pkg::personaldata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custome_msgs_pkg::personaldata_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOME_MSGS_PKG_MESSAGE_PERSONALDATA_H
