// Generated by gencpp from file c_srv/AddTwoInts.msg
// DO NOT EDIT!


#ifndef C_SRV_MESSAGE_ADDTWOINTS_H
#define C_SRV_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <c_srv/AddTwoIntsRequest.h>
#include <c_srv/AddTwoIntsResponse.h>


namespace c_srv
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace c_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::c_srv::AddTwoInts > {
  static const char* value()
  {
    return "875493d2ec8f0bdc18c62960322c94b7";
  }

  static const char* value(const ::c_srv::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::c_srv::AddTwoInts > {
  static const char* value()
  {
    return "c_srv/AddTwoInts";
  }

  static const char* value(const ::c_srv::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::c_srv::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::c_srv::AddTwoInts >
template<>
struct MD5Sum< ::c_srv::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::c_srv::AddTwoInts >::value();
  }
  static const char* value(const ::c_srv::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::c_srv::AddTwoIntsRequest> should match
// service_traits::DataType< ::c_srv::AddTwoInts >
template<>
struct DataType< ::c_srv::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::c_srv::AddTwoInts >::value();
  }
  static const char* value(const ::c_srv::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::c_srv::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::c_srv::AddTwoInts >
template<>
struct MD5Sum< ::c_srv::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::c_srv::AddTwoInts >::value();
  }
  static const char* value(const ::c_srv::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::c_srv::AddTwoIntsResponse> should match
// service_traits::DataType< ::c_srv::AddTwoInts >
template<>
struct DataType< ::c_srv::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::c_srv::AddTwoInts >::value();
  }
  static const char* value(const ::c_srv::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // C_SRV_MESSAGE_ADDTWOINTS_H
