// Generated by gencpp from file c_srv/ProcessDataRequest.msg
// DO NOT EDIT!


#ifndef C_SRV_MESSAGE_PROCESSDATAREQUEST_H
#define C_SRV_MESSAGE_PROCESSDATAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace c_srv
{
template <class ContainerAllocator>
struct ProcessDataRequest_
{
  typedef ProcessDataRequest_<ContainerAllocator> Type;

  ProcessDataRequest_()
    : readings()  {
    }
  ProcessDataRequest_(const ContainerAllocator& _alloc)
    : readings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _readings_type;
  _readings_type readings;





  typedef boost::shared_ptr< ::c_srv::ProcessDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::c_srv::ProcessDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessDataRequest_

typedef ::c_srv::ProcessDataRequest_<std::allocator<void> > ProcessDataRequest;

typedef boost::shared_ptr< ::c_srv::ProcessDataRequest > ProcessDataRequestPtr;
typedef boost::shared_ptr< ::c_srv::ProcessDataRequest const> ProcessDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::c_srv::ProcessDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::c_srv::ProcessDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::c_srv::ProcessDataRequest_<ContainerAllocator1> & lhs, const ::c_srv::ProcessDataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.readings == rhs.readings;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::c_srv::ProcessDataRequest_<ContainerAllocator1> & lhs, const ::c_srv::ProcessDataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace c_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::c_srv::ProcessDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::c_srv::ProcessDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::c_srv::ProcessDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::c_srv::ProcessDataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::c_srv::ProcessDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::c_srv::ProcessDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::c_srv::ProcessDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "790f38aeabddcc73abb1ebbc6fb37849";
  }

  static const char* value(const ::c_srv::ProcessDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x790f38aeabddcc73ULL;
  static const uint64_t static_value2 = 0xabb1ebbc6fb37849ULL;
};

template<class ContainerAllocator>
struct DataType< ::c_srv::ProcessDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c_srv/ProcessDataRequest";
  }

  static const char* value(const ::c_srv::ProcessDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::c_srv::ProcessDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] readings\n"
;
  }

  static const char* value(const ::c_srv::ProcessDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::c_srv::ProcessDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.readings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::c_srv::ProcessDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::c_srv::ProcessDataRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "readings: ";
    if (v.readings.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.readings.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.readings[i]);
    }
    if (v.readings.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // C_SRV_MESSAGE_PROCESSDATAREQUEST_H
