// Generated by gencpp from file c_srv/ProcessDataResponse.msg
// DO NOT EDIT!


#ifndef C_SRV_MESSAGE_PROCESSDATARESPONSE_H
#define C_SRV_MESSAGE_PROCESSDATARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace c_srv
{
template <class ContainerAllocator>
struct ProcessDataResponse_
{
  typedef ProcessDataResponse_<ContainerAllocator> Type;

  ProcessDataResponse_()
    : avr(0.0)
    , max(0.0)
    , min(0.0)  {
    }
  ProcessDataResponse_(const ContainerAllocator& _alloc)
    : avr(0.0)
    , max(0.0)
    , min(0.0)  {
  (void)_alloc;
    }



   typedef float _avr_type;
  _avr_type avr;

   typedef float _max_type;
  _max_type max;

   typedef float _min_type;
  _min_type min;





  typedef boost::shared_ptr< ::c_srv::ProcessDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::c_srv::ProcessDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessDataResponse_

typedef ::c_srv::ProcessDataResponse_<std::allocator<void> > ProcessDataResponse;

typedef boost::shared_ptr< ::c_srv::ProcessDataResponse > ProcessDataResponsePtr;
typedef boost::shared_ptr< ::c_srv::ProcessDataResponse const> ProcessDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::c_srv::ProcessDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::c_srv::ProcessDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::c_srv::ProcessDataResponse_<ContainerAllocator1> & lhs, const ::c_srv::ProcessDataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.avr == rhs.avr &&
    lhs.max == rhs.max &&
    lhs.min == rhs.min;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::c_srv::ProcessDataResponse_<ContainerAllocator1> & lhs, const ::c_srv::ProcessDataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace c_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::c_srv::ProcessDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::c_srv::ProcessDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::c_srv::ProcessDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::c_srv::ProcessDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::c_srv::ProcessDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::c_srv::ProcessDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::c_srv::ProcessDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea69c49f8d343f438519186d8161a15e";
  }

  static const char* value(const ::c_srv::ProcessDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea69c49f8d343f43ULL;
  static const uint64_t static_value2 = 0x8519186d8161a15eULL;
};

template<class ContainerAllocator>
struct DataType< ::c_srv::ProcessDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c_srv/ProcessDataResponse";
  }

  static const char* value(const ::c_srv::ProcessDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::c_srv::ProcessDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 avr\n"
"float32 max\n"
"float32 min\n"
;
  }

  static const char* value(const ::c_srv::ProcessDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::c_srv::ProcessDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.avr);
      stream.next(m.max);
      stream.next(m.min);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::c_srv::ProcessDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::c_srv::ProcessDataResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "avr: ";
    Printer<float>::stream(s, indent + "  ", v.avr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max: ";
    Printer<float>::stream(s, indent + "  ", v.max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "min: ";
    Printer<float>::stream(s, indent + "  ", v.min);
  }
};

} // namespace message_operations
} // namespace ros

#endif // C_SRV_MESSAGE_PROCESSDATARESPONSE_H
