// Generated by gencpp from file c_srv/ProcessData.msg
// DO NOT EDIT!


#ifndef C_SRV_MESSAGE_PROCESSDATA_H
#define C_SRV_MESSAGE_PROCESSDATA_H

#include <ros/service_traits.h>


#include <c_srv/ProcessDataRequest.h>
#include <c_srv/ProcessDataResponse.h>


namespace c_srv
{

struct ProcessData
{

typedef ProcessDataRequest Request;
typedef ProcessDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessData
} // namespace c_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::c_srv::ProcessData > {
  static const char* value()
  {
    return "16f2efda5f60ebda61797ff9a741ba29";
  }

  static const char* value(const ::c_srv::ProcessData&) { return value(); }
};

template<>
struct DataType< ::c_srv::ProcessData > {
  static const char* value()
  {
    return "c_srv/ProcessData";
  }

  static const char* value(const ::c_srv::ProcessData&) { return value(); }
};


// service_traits::MD5Sum< ::c_srv::ProcessDataRequest> should match
// service_traits::MD5Sum< ::c_srv::ProcessData >
template<>
struct MD5Sum< ::c_srv::ProcessDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::c_srv::ProcessData >::value();
  }
  static const char* value(const ::c_srv::ProcessDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::c_srv::ProcessDataRequest> should match
// service_traits::DataType< ::c_srv::ProcessData >
template<>
struct DataType< ::c_srv::ProcessDataRequest>
{
  static const char* value()
  {
    return DataType< ::c_srv::ProcessData >::value();
  }
  static const char* value(const ::c_srv::ProcessDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::c_srv::ProcessDataResponse> should match
// service_traits::MD5Sum< ::c_srv::ProcessData >
template<>
struct MD5Sum< ::c_srv::ProcessDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::c_srv::ProcessData >::value();
  }
  static const char* value(const ::c_srv::ProcessDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::c_srv::ProcessDataResponse> should match
// service_traits::DataType< ::c_srv::ProcessData >
template<>
struct DataType< ::c_srv::ProcessDataResponse>
{
  static const char* value()
  {
    return DataType< ::c_srv::ProcessData >::value();
  }
  static const char* value(const ::c_srv::ProcessDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // C_SRV_MESSAGE_PROCESSDATA_H
